image: Visual Studio 2019
skip_tags: true

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore MouseTrap.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build:
  project: MouseTrap.sln

platform:
  - x64

configuration:
  - Release

after_build:
  - cmd: "\"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe\" \"Setup\\MouseTrapSetup.iss\""

artifacts:
- path: 'Release\MouseTrap-*.exe'

deploy:
  provider: GitHub
  auth_token:
    secure: wcCLjXIsoiaVetYk+2q3suieP6B0oou+0TSC6cSEyVIUbsVxsvpUPwQpPHEE1h18
  artifact: /Release\\MouseTrap-.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master