image: Visual Studio 2019


install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore MouseTrap.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build:
  project: MouseTrap.sln

platform:
  - x64

configuration:
  - Release

after_build:
  - cmd: "\"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe\" \"Setup\\MouseTrapSetup.iss\""

artifacts:
- path: 'Release\MouseTrap-*.exe'

deploy:
  provider: GitHub
  auth_token:
    secure: fPvma5Dn9PV65Juan1Lx9AcxoGwLSRIxSjYZGZ46EvI8QoXEUGH0T0fnJDYF5vbM
  artifact: Release\\MouseTrap-.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true